In [1]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import seaborn

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.model_selection import GridSearchCV

from sklearn.ensemble import RandomForestClassifier as RF

In [2]:
!dir inputs

 ドライブ C のボリューム ラベルがありません。
 ボリューム シリアル番号は 5AD7-2869 です

 C:\Users\yanai\OneDrive\ドキュメント\Python Scripts\Signate\【練習問題】林型の分類\inputs のディレクトリ

11/03/2021  19:26    <DIR>          .
11/03/2021  19:26    <DIR>          ..
11/03/2021  18:56         2,559,052 sample_submit.csv
11/03/2021  18:56        38,982,818 test.tsv
11/03/2021  18:56        39,562,946 train.tsv
               3 個のファイル          81,104,816 バイト
               2 個のディレクトリ  176,735,768,576 バイトの空き領域

In [3]:
train = pd.read_csv('inputs/train.tsv', sep='\t', index_col=0)
train

,Elevation,Aspect,Slope,Horizontal_Distance_To_Hydrology,Vertical_Distance_To_Hydrology,Horizontal_Distance_To_Roadways,Hillshade_9am,Hillshade_Noon,Hillshade_3pm,Horizontal_Distance_To_Fire_Points,...,Soil_Type32,Soil_Type33,Soil_Type34,Soil_Type35,Soil_Type36,Soil_Type37,Soil_Type38,Soil_Type39,Soil_Type40,Cover_Type
0,3189,202,28,518,-25,1723,194,251,175,3599,...,0,0,0,0,0,0,0,0,0,1
1,3220,14,4,90,5,5940,216,231,153,1153,...,0,0,0,0,0,0,0,0,0,1
3,3221,168,16,30,11,2577,231,244,139,2761,...,0,0,0,0,0,0,0,0,0,7
4,2967,308,14,201,42,1360,181,230,189,3164,...,0,0,0,0,0,0,0,0,0,1
6,3009,16,15,150,16,3650,206,208,137,5053,...,0,0,0,0,0,0,0,0,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
581005,3018,135,9,794,132,5891,235,236,133,5496,...,0,0,0,0,0,0,0,0,0,2
581007,3070,8,2,120,3,5334,217,235,155,2536,...,0,0,0,0,0,0,0,0,0,1
581009,2735,14,24,60,26,2227,190,184,123,360,...,0,0,0,0,0,0,0,0,0,2
581010,2813,44,17,150,32,1396,222,201,109,1254,...,0,0,0,0,0,0,0,0,0,2
581011,2900,90,15,532,89,1772,242,215,99,2794,...,0,0,0,0,0,0,0,0,0,2

In [4]:
train.shape

(290506, 55)

In [5]:
train.describe()

,Elevation,Aspect,Slope,Horizontal_Distance_To_Hydrology,Vertical_Distance_To_Hydrology,Horizontal_Distance_To_Roadways,Hillshade_9am,Hillshade_Noon,Hillshade_3pm,Horizontal_Distance_To_Fire_Points,...,Soil_Type32,Soil_Type33,Soil_Type34,Soil_Type35,Soil_Type36,Soil_Type37,Soil_Type38,Soil_Type39,Soil_Type40,Cover_Type
count,290506.000000,290506.000000,290506.000000,290506.000000,290506.000000,290506.000000,290506.000000,290506.000000,290506.000000,290506.000000,...,290506.000000,290506.000000,290506.000000,290506.000000,290506.000000,290506.000000,290506.000000,290506.000000,290506.000000,290506.000000
mean,2959.006193,155.548188,14.101158,269.546195,46.409558,2346.371789,212.156434,223.346172,142.543762,1978.862619,...,0.090432,0.077940,0.003009,0.003315,0.000210,0.000506,0.026629,0.023903,0.014685,2.052316
std,279.811177,111.840102,7.494155,212.774037,58.374441,1557.018229,26.762808,19.777016,38.251073,1324.192989,...,0.286800,0.268077,0.054768,0.057480,0.014489,0.022489,0.160998,0.152748,0.120288,1.396138
min,1859.000000,0.000000,0.000000,0.000000,-166.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
25%,2809.000000,58.000000,9.000000,108.000000,7.000000,1103.000000,198.000000,213.000000,119.000000,1022.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
50%,2995.000000,127.000000,13.000000,218.000000,29.000000,1994.000000,218.000000,226.000000,143.000000,1707.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000
75%,3163.000000,260.000000,18.000000,390.000000,69.000000,3319.000000,231.000000,237.000000,168.000000,2549.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000
max,3858.000000,360.000000,66.000000,1383.000000,601.000000,7112.000000,254.000000,254.000000,254.000000,7172.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,7.000000

In [6]:
X = train.drop('Cover_Type', axis=1)
y = train['Cover_Type']

In [7]:
X

,Elevation,Aspect,Slope,Horizontal_Distance_To_Hydrology,Vertical_Distance_To_Hydrology,Horizontal_Distance_To_Roadways,Hillshade_9am,Hillshade_Noon,Hillshade_3pm,Horizontal_Distance_To_Fire_Points,...,Soil_Type31,Soil_Type32,Soil_Type33,Soil_Type34,Soil_Type35,Soil_Type36,Soil_Type37,Soil_Type38,Soil_Type39,Soil_Type40
0,3189,202,28,518,-25,1723,194,251,175,3599,...,0,0,0,0,0,0,0,0,0,0
1,3220,14,4,90,5,5940,216,231,153,1153,...,0,0,0,0,0,0,0,0,0,0
3,3221,168,16,30,11,2577,231,244,139,2761,...,0,0,0,0,0,0,0,0,0,0
4,2967,308,14,201,42,1360,181,230,189,3164,...,0,0,0,0,0,0,0,0,0,0
6,3009,16,15,150,16,3650,206,208,137,5053,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
581005,3018,135,9,794,132,5891,235,236,133,5496,...,0,0,0,0,0,0,0,0,0,0
581007,3070,8,2,120,3,5334,217,235,155,2536,...,0,0,0,0,0,0,0,0,0,0
581009,2735,14,24,60,26,2227,190,184,123,360,...,1,0,0,0,0,0,0,0,0,0
581010,2813,44,17,150,32,1396,222,201,109,1254,...,0,0,0,0,0,0,0,0,0,0
581011,2900,90,15,532,89,1772,242,215,99,2794,...,0,0,0,0,0,0,0,0,0,0

In [8]:
X_train, X_val, y_train, y_val = train_test_split(X, y, random_state=0)

In [9]:
X_train

,Elevation,Aspect,Slope,Horizontal_Distance_To_Hydrology,Vertical_Distance_To_Hydrology,Horizontal_Distance_To_Roadways,Hillshade_9am,Hillshade_Noon,Hillshade_3pm,Horizontal_Distance_To_Fire_Points,...,Soil_Type31,Soil_Type32,Soil_Type33,Soil_Type34,Soil_Type35,Soil_Type36,Soil_Type37,Soil_Type38,Soil_Type39,Soil_Type40
13028,3151,271,23,175,21,4631,155,240,222,3354,...,0,0,0,0,0,0,0,0,0,0
42308,2998,42,13,384,94,4754,222,210,121,3650,...,0,0,0,0,0,0,0,0,0,0
300893,2788,85,30,201,123,201,246,174,34,1718,...,0,0,0,0,0,0,0,0,0,0
30581,3137,331,19,85,16,1366,172,213,179,2310,...,0,0,0,0,0,0,0,0,0,0
40389,3247,22,13,108,7,6120,212,213,136,361,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
423192,3064,26,14,384,60,2914,213,208,129,5872,...,0,0,0,0,0,0,0,0,0,0
173034,2986,83,19,120,-4,872,243,205,85,882,...,0,0,0,0,0,0,0,0,0,0
245112,3240,346,8,108,12,4119,205,228,161,1189,...,0,0,0,0,0,0,0,0,1,0
304600,2802,73,17,30,2,3178,237,205,93,1880,...,0,0,0,0,0,0,0,0,0,0
236060,3208,304,25,30,9,2362,145,219,211,2910,...,0,0,0,0,0,0,0,0,0,0

In [10]:
y_train

13028     1
42308     2
300893    2
30581     1
40389     1
         ..
423192    2
173034    1
245112    1
304600    2
236060    1
Name: Cover_Type, Length: 217879, dtype: int64

In [11]:
rf_model = RF()

In [12]:
param_grid = {
    'n_estimators': [200, 500],
    'max_features': ['auto', 'sqrt', 'log2'],
    'max_depth' : [4,5,6,7,8],
    'criterion' :['gini', 'entropy']
}

In [15]:
rscv = GridSearchCV(rf_model, param_grid, verbose=3)

In [ ]:
rscv.fit(X_train, y_train)

Fitting 5 folds for each of 60 candidates, totalling 300 fits
[CV] criterion=gini, max_depth=4, max_features=auto, n_estimators=200

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.

[CV]  criterion=gini, max_depth=4, max_features=auto, n_estimators=200, score=0.668, total=  21.7s
[CV] criterion=gini, max_depth=4, max_features=auto, n_estimators=200

[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:   21.6s remaining:    0.0s

[CV]  criterion=gini, max_depth=4, max_features=auto, n_estimators=200, score=0.682, total=  21.3s
[CV] criterion=gini, max_depth=4, max_features=auto, n_estimators=200

[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:   42.9s remaining:    0.0s

[CV]  criterion=gini, max_depth=4, max_features=auto, n_estimators=200, score=0.673, total=  26.3s
[CV] criterion=gini, max_depth=4, max_features=auto, n_estimators=200
[CV]  criterion=gini, max_depth=4, max_features=auto, n_estimators=200, score=0.673, total=  27.7s
[CV] criterion=gini, max_depth=4, max_features=auto, n_estimators=200
[CV]  criterion=gini, max_depth=4, max_features=auto, n_estimators=200, score=0.671, total=  27.0s
[CV] criterion=gini, max_depth=4, max_features=auto, n_estimators=500

In [ ]:
predict = rscv.predict(X_test)

In [ ]:
accuracy_score(prefict, y_test)

In [ ]:
predict = rscv.predict(X_val)

In [ ]:
predict

In [ ]:
y_val