In [1]:
import pandas as pd

In [2]:
!dir inputs

 ドライブ C のボリューム ラベルがありません。
 ボリューム シリアル番号は 5AD7-2869 です

 C:\Users\yanai\OneDrive\ドキュメント\Python Scripts\Signate\【練習問題】林型の分類\inputs のディレクトリ

11/03/2021  19:26    <DIR>          .
11/03/2021  19:26    <DIR>          ..
11/03/2021  18:56         2,559,052 sample_submit.csv
11/03/2021  18:56        38,982,818 test.tsv
11/03/2021  18:56        39,562,946 train.tsv
               3 個のファイル          81,104,816 バイト
               2 個のディレクトリ  169,714,458,624 バイトの空き領域

In [3]:
train = pd.read_csv('inputs/train.tsv', sep='\t', index_col=0)
train

,Elevation,Aspect,Slope,Horizontal_Distance_To_Hydrology,Vertical_Distance_To_Hydrology,Horizontal_Distance_To_Roadways,Hillshade_9am,Hillshade_Noon,Hillshade_3pm,Horizontal_Distance_To_Fire_Points,...,Soil_Type32,Soil_Type33,Soil_Type34,Soil_Type35,Soil_Type36,Soil_Type37,Soil_Type38,Soil_Type39,Soil_Type40,Cover_Type
0,3189,202,28,518,-25,1723,194,251,175,3599,...,0,0,0,0,0,0,0,0,0,1
1,3220,14,4,90,5,5940,216,231,153,1153,...,0,0,0,0,0,0,0,0,0,1
3,3221,168,16,30,11,2577,231,244,139,2761,...,0,0,0,0,0,0,0,0,0,7
4,2967,308,14,201,42,1360,181,230,189,3164,...,0,0,0,0,0,0,0,0,0,1
6,3009,16,15,150,16,3650,206,208,137,5053,...,0,0,0,0,0,0,0,0,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
581005,3018,135,9,794,132,5891,235,236,133,5496,...,0,0,0,0,0,0,0,0,0,2
581007,3070,8,2,120,3,5334,217,235,155,2536,...,0,0,0,0,0,0,0,0,0,1
581009,2735,14,24,60,26,2227,190,184,123,360,...,0,0,0,0,0,0,0,0,0,2
581010,2813,44,17,150,32,1396,222,201,109,1254,...,0,0,0,0,0,0,0,0,0,2
581011,2900,90,15,532,89,1772,242,215,99,2794,...,0,0,0,0,0,0,0,0,0,2

In [4]:
train['Cover_Type'].value_counts()

2    141843
1    105713
3     17856
7     10223
6      8715
5      4768
4      1388
Name: Cover_Type, dtype: int64

In [5]:
from pycaret.classification import *

In [6]:
exp1 = setup(data = train, target = 'Cover_Type', session_id = 123)

In [7]:
compare_models()

In [8]:
# knn = create_model('knn')

IntProgress(value=0, description='Processing: ', max=4)

Initiated  . . . . . . . . . . . . . . . . . .                21:00:48
Status     . . . . . . . . . . . . . . . . . .        Fitting 10 Folds
Estimator  . . . . . . . . . . . . . . . . . .  K Neighbors Classifier

Empty DataFrame
Columns: [Accuracy, AUC, Recall, Prec., F1, Kappa, MCC]
Index: []

KeyboardInterrupt:

In [ ]:
# tuned_knn = tune_model(knn)

In [ ]:
# test = pd.read_csv('inputs/test.tsv', sep='\t', index_col=0)
# test

In [ ]:
# knn_tunefinal_knn
# plot_model(tuned_knn, plot = 'error')

In [ ]:
# evaluate_model(tuned_knn)

In [ ]:
# knn_tunefinal_knn = finalize_model(tuned_knn)

In [ ]:
# evaluate_model

In [ ]:
# predict_model(tuned_knn)