# PART2 データをもう少し詳しく見てみよう
## おまじない

In [1]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
%matplotlib inline

## データの読み込み
- train.csvを読み込みましょう
- 読み込んだものは変数trainに代入しましょう

In [2]:
train = pd.read_csv('train.csv')

## trainの先頭行を見てみましょう

In [3]:
train.head()

,datetime,y,week,soldout,name,kcal,remarks,event,payday,weather,precipitation,temperature
0,2013-11-18,90,月,0,厚切りイカフライ,NaN,NaN,NaN,NaN,快晴,--,19.8
1,2013-11-19,101,火,1,手作りヒレカツ,NaN,NaN,NaN,NaN,快晴,--,17.0
2,2013-11-20,118,水,0,白身魚唐揚げ野菜あん,NaN,NaN,NaN,NaN,快晴,--,15.5
3,2013-11-21,120,木,1,若鶏ピリ辛焼,NaN,NaN,NaN,NaN,快晴,--,15.2
4,2013-11-22,130,金,1,ビッグメンチカツ,NaN,NaN,NaN,NaN,快晴,--,16.1

## 基本統計量を確認してみましょう
- describe関数を使います

In [4]:
train.describe()

                y     soldout        kcal  payday  temperature
count  207.000000  207.000000  166.000000    10.0   207.000000
mean    86.623188    0.449275  404.409639     1.0    19.252174
std     32.882448    0.498626   29.884641     0.0     8.611365
min     29.000000    0.000000  315.000000     1.0     1.200000
25%     57.000000    0.000000  386.000000     1.0    11.550000
50%     78.000000    0.000000  408.500000     1.0    19.800000
75%    113.000000    1.000000  426.000000     1.0    26.100000
max    171.000000    1.000000  462.000000     1.0    34.600000

In [5]:
train.describe(include='O')

         datetime week      name   remarks event weather precipitation
count         207  207       207        21    14     207           207
unique        207    5       156         6     2       7             8
top     2014-7-18    水  タンドリーチキン  お楽しみメニュー  ママの会       曇            --
freq            1   43         6        12     9      53           169

In [6]:
train.describe(include='all')

,datetime,y,week,soldout,name,kcal,remarks,event,payday,weather,precipitation,temperature
count,207,207.000000,207,207.000000,207,166.000000,21,14,10.0,207,207,207.000000
unique,207,NaN,5,NaN,156,NaN,6,2,NaN,7,8,NaN
top,2014-7-18,NaN,水,NaN,タンドリーチキン,NaN,お楽しみメニュー,ママの会,NaN,曇,--,NaN
freq,1,NaN,43,NaN,6,NaN,12,9,NaN,53,169,NaN
mean,NaN,86.623188,NaN,0.449275,NaN,404.409639,NaN,NaN,1.0,NaN,NaN,19.252174
std,NaN,32.882448,NaN,0.498626,NaN,29.884641,NaN,NaN,0.0,NaN,NaN,8.611365
min,NaN,29.000000,NaN,0.000000,NaN,315.000000,NaN,NaN,1.0,NaN,NaN,1.200000
25%,NaN,57.000000,NaN,0.000000,NaN,386.000000,NaN,NaN,1.0,NaN,NaN,11.550000
50%,NaN,78.000000,NaN,0.000000,NaN,408.500000,NaN,NaN,1.0,NaN,NaN,19.800000
75%,NaN,113.000000,NaN,1.000000,NaN,426.000000,NaN,NaN,1.0,NaN,NaN,26.100000
max,NaN,171.000000,NaN,1.000000,NaN,462.000000,NaN,NaN,1.0,NaN,NaN,34.600000

## データの型を確認してみましょう
- info関数を使います

In [7]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 207 entries, 0 to 206
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   datetime       207 non-null    object
 1   y              207 non-null    int64
 2   week           207 non-null    object
 3   soldout        207 non-null    int64
 4   name           207 non-null    object
 5   kcal           166 non-null    float64
 6   remarks        21 non-null     object
 7   event          14 non-null     object
 8   payday         10 non-null     float64
 9   weather        207 non-null    object
 10  precipitation  207 non-null    object
 11  temperature    207 non-null    float64
dtypes: float64(3), int64(2), object(7)
memory usage: 19.5+ KB

## 1つのカラムだけに注目してみましょう
- ここでは"y"というカラムを見てみましょう

In [8]:
train['y']

0       90
1      101
2      118
3      120
4      130
      ...
202     59
203     50
204     45
205     56
206     40
Name: y, Length: 207, dtype: int64

## yの平均と中央値を見てみましょう
- 平均値はmean関数、中央値はmedian関数を使います

In [17]:
train.describe()

                y     soldout        kcal  payday  temperature
count  207.000000  207.000000  166.000000    10.0   207.000000
mean    86.623188    0.449275  404.409639     1.0    19.252174
std     32.882448    0.498626   29.884641     0.0     8.611365
min     29.000000    0.000000  315.000000     1.0     1.200000
25%     57.000000    0.000000  386.000000     1.0    11.550000
50%     78.000000    0.000000  408.500000     1.0    19.800000
75%    113.000000    1.000000  426.000000     1.0    26.100000
max    171.000000    1.000000  462.000000     1.0    34.600000

In [12]:
train['y'].mean()

86.6231884057971

In [13]:
train['y'].median()

78.0

In [15]:
train.describe()['y']['mean']

86.6231884057971

## yの値が150以上のデータのみを見てみましょう

In [19]:
train[train['y'] >= 150]

,datetime,y,week,soldout,name,kcal,remarks,event,payday,weather,precipitation,temperature
8,2013-11-28,151,木,0,ハンバーグ,NaN,NaN,NaN,NaN,薄曇,--,17.7
10,2013-12-2,151,月,1,マーボ豆腐,NaN,NaN,NaN,NaN,快晴,--,13.8
11,2013-12-3,153,火,1,厚揚げ豚生姜炒め,NaN,NaN,NaN,NaN,快晴,--,13.9
12,2013-12-4,151,水,1,クリームチーズ入りメンチ,NaN,NaN,NaN,NaN,晴れ,--,13.5
13,2013-12-5,171,木,0,鶏のカッシュナッツ炒め,NaN,NaN,NaN,NaN,快晴,--,13.8
15,2013-12-9,165,月,1,ハンバーグデミソース,NaN,NaN,NaN,NaN,曇,--,9.1
16,2013-12-10,155,火,0,やわらかロースのサムジョン,NaN,NaN,NaN,1.0,曇,0.5,7.1
17,2013-12-11,157,水,0,五目御飯,NaN,NaN,NaN,NaN,曇,--,11.0
20,2013-12-16,160,月,0,カキフライタルタル,NaN,NaN,NaN,NaN,快晴,--,11.3
23,2013-12-19,151,木,0,ポーク味噌焼き,NaN,NaN,NaN,NaN,雨,0.5,6.8

## 曜日が月となっているデータのみを見てみましょう

In [20]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 207 entries, 0 to 206
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   datetime       207 non-null    object
 1   y              207 non-null    int64
 2   week           207 non-null    object
 3   soldout        207 non-null    int64
 4   name           207 non-null    object
 5   kcal           166 non-null    float64
 6   remarks        21 non-null     object
 7   event          14 non-null     object
 8   payday         10 non-null     float64
 9   weather        207 non-null    object
 10  precipitation  207 non-null    object
 11  temperature    207 non-null    float64
dtypes: float64(3), int64(2), object(7)
memory usage: 19.5+ KB

In [21]:
train['week'].value_counts()

水    43
木    43
金    41
火    41
月    39
Name: week, dtype: int64

In [24]:
train[train['week'] == '火']

,datetime,y,week,soldout,name,kcal,remarks,event,payday,weather,precipitation,temperature
1,2013-11-19,101,火,1,手作りヒレカツ,NaN,NaN,NaN,NaN,快晴,--,17.0
6,2013-11-26,145,火,0,豚のスタミナ炒め,NaN,NaN,NaN,NaN,快晴,--,17.9
11,2013-12-3,153,火,1,厚揚げ豚生姜炒め,NaN,NaN,NaN,NaN,快晴,--,13.9
16,2013-12-10,155,火,0,やわらかロースのサムジョン,NaN,NaN,NaN,1.0,曇,0.5,7.1
21,2013-12-17,145,火,0,手作りヒレカツ,NaN,NaN,ママの会,NaN,曇,--,10.8
25,2013-12-24,122,火,0,さっくりメンチカツ,NaN,NaN,NaN,NaN,快晴,--,11.5
28,2014-1-7,131,火,0,カレー入りソーセージカツ,404.0,NaN,NaN,NaN,快晴,--,7.3
32,2014-1-14,129,火,1,鶏の照り焼きマスタード,376.0,NaN,NaN,NaN,晴れ,--,5.8
37,2014-1-21,129,火,1,サバ焼味噌掛け,447.0,NaN,NaN,NaN,快晴,--,10.4
42,2014-1-28,120,火,0,海老フライタルタル,445.0,NaN,NaN,NaN,快晴,--,12.6
47,2014-2-4,121,火,1,さわら焼味噌掛け,430.0,NaN,NaN,NaN,雨,0,3.8
56,2014-2-18,99,火,0,海老フライとホタテ串カツ,426.0,NaN,NaN,NaN,晴れ,--,6.8
61,2014-2-25,104,火,0,マーボ豆腐,396.0,NaN,NaN,NaN,快晴,--,10.5
66,2014-3-4,100,火,1,回鍋肉,413.0,NaN,NaN,NaN,晴れ,--,8.3
71,2014-3-11,89,火,0,肉じゃが,397.0,NaN,NaN,NaN,快晴,--,8.7
76,2014-3-18,90,火,1,チーズ入りハンバーグ,400.0,NaN,NaN,NaN,晴れ,--,18.9
80,2014-3-25,77,火,0,手作りひれかつ,407.0,NaN,NaN,NaN,快晴,--,18.9
85,2014-4-1,125,火,1,メンチカツ,377.0,NaN,NaN,NaN,薄曇,--,16.1
90,2014-4-8,96,火,1,肉団子のシチュー,353.0,NaN,NaN,NaN,快晴,--,20.1
95,2014-4-15,82,火,0,ポーク生姜焼き,370.0,NaN,NaN,NaN,快晴,--,19.7
100,2014-4-22,78,火,1,マーボ豆腐,382.0,NaN,NaN,NaN,曇,--,18.8
112,2014-5-13,70,火,1,白身魚唐揚げ野菜餡かけ,428.0,NaN,NaN,NaN,雨,0,18.6
117,2014-5-20,71,火,0,鶏の味噌漬け焼き,425.0,NaN,NaN,NaN,薄曇,--,23.9
122,2014-5-27,79,火,0,牛肉すき焼き風,423.0,NaN,NaN,NaN,曇,--,23.7
127,2014-6-3,59,火,0,ゴーヤチャンプルー,418.0,NaN,NaN,NaN,薄曇,--,27.0
132,2014-6-10,56,火,0,カレイ唐揚げ野菜餡かけ,426.0,NaN,NaN,1.0,曇,--,25.5
137,2014-6-17,63,火,0,ポークソテー韓国ソース,427.0,NaN,NaN,NaN,薄曇,--,27.6
142,2014-6-24,61,火,0,鶏のトマトシチュー,430.0,NaN,NaN,NaN,曇,0,23.7
147,2014-7-1,54,火,0,カレイ唐揚げ夏野菜あん,362.0,NaN,NaN,NaN,曇,--,28.3
152,2014-7-8,56,火,0,かじきの甘辛煮,370.0,NaN,NaN,NaN,晴れ,--,29.7
157,2014-7-15,51,火,0,豚冷シャブ野菜添え,324.0,NaN,NaN,NaN,晴れ,--,30.3
161,2014-7-22,53,火,0,チンジャオロース,409.0,NaN,NaN,NaN,晴れ,--,30.2
166,2014-7-29,52,火,0,バーベキューチキン,449.0,NaN,NaN,NaN,晴れ,--,30.4
171,2014-8-5,54,火,1,鶏肉のカレー唐揚,400.0,NaN,NaN,NaN,快晴,--,34.3
176,2014-8-12,40,火,1,厚切ハムカツ,400.0,NaN,NaN,NaN,雨,0,29.4
178,2014-8-19,53,火,1,牛スキヤキ,385.0,NaN,NaN,NaN,晴れ,--,33.3
183,2014-8-26,68,火,0,キーマカレー,400.0,NaN,NaN,NaN,雨,0,26.2
188,2014-9-2,68,火,1,名古屋味噌カツ,440.0,手作りの味,NaN,NaN,晴れ,--,29.1
193,2014-9-9,63,火,0,ハンバーグデミソース,460.0,NaN,NaN,NaN,晴れ,--,26.8
197,2014-9-16,56,火,0,チーズメンチカツ,438.0,NaN,NaN,NaN,晴れ,--,28.8
206,2014-9-30,40,火,0,鶏肉とカシューナッツ炒め,398.0,NaN,NaN,NaN,快晴,--,28.1

## 曜日が火となっているデータをyで昇順・降順にして見てみましょう
- ソートはsort_values関数を使います。sort_values(by="XXX")と書きます
- 降順にしたい場合はカッコの中にオプションとしてascending=Falseを書きます

In [23]:
train[train['week'] == '火'].sort_values(by='y')

,datetime,y,week,soldout,name,kcal,remarks,event,payday,weather,precipitation,temperature
206,2014-9-30,40,火,0,鶏肉とカシューナッツ炒め,398.0,NaN,NaN,NaN,快晴,--,28.1
176,2014-8-12,40,火,1,厚切ハムカツ,400.0,NaN,NaN,NaN,雨,0,29.4
157,2014-7-15,51,火,0,豚冷シャブ野菜添え,324.0,NaN,NaN,NaN,晴れ,--,30.3
166,2014-7-29,52,火,0,バーベキューチキン,449.0,NaN,NaN,NaN,晴れ,--,30.4
178,2014-8-19,53,火,1,牛スキヤキ,385.0,NaN,NaN,NaN,晴れ,--,33.3
161,2014-7-22,53,火,0,チンジャオロース,409.0,NaN,NaN,NaN,晴れ,--,30.2
147,2014-7-1,54,火,0,カレイ唐揚げ夏野菜あん,362.0,NaN,NaN,NaN,曇,--,28.3
171,2014-8-5,54,火,1,鶏肉のカレー唐揚,400.0,NaN,NaN,NaN,快晴,--,34.3
132,2014-6-10,56,火,0,カレイ唐揚げ野菜餡かけ,426.0,NaN,NaN,1.0,曇,--,25.5
152,2014-7-8,56,火,0,かじきの甘辛煮,370.0,NaN,NaN,NaN,晴れ,--,29.7
197,2014-9-16,56,火,0,チーズメンチカツ,438.0,NaN,NaN,NaN,晴れ,--,28.8
127,2014-6-3,59,火,0,ゴーヤチャンプルー,418.0,NaN,NaN,NaN,薄曇,--,27.0
142,2014-6-24,61,火,0,鶏のトマトシチュー,430.0,NaN,NaN,NaN,曇,0,23.7
137,2014-6-17,63,火,0,ポークソテー韓国ソース,427.0,NaN,NaN,NaN,薄曇,--,27.6
193,2014-9-9,63,火,0,ハンバーグデミソース,460.0,NaN,NaN,NaN,晴れ,--,26.8
188,2014-9-2,68,火,1,名古屋味噌カツ,440.0,手作りの味,NaN,NaN,晴れ,--,29.1
183,2014-8-26,68,火,0,キーマカレー,400.0,NaN,NaN,NaN,雨,0,26.2
112,2014-5-13,70,火,1,白身魚唐揚げ野菜餡かけ,428.0,NaN,NaN,NaN,雨,0,18.6
117,2014-5-20,71,火,0,鶏の味噌漬け焼き,425.0,NaN,NaN,NaN,薄曇,--,23.9
80,2014-3-25,77,火,0,手作りひれかつ,407.0,NaN,NaN,NaN,快晴,--,18.9
100,2014-4-22,78,火,1,マーボ豆腐,382.0,NaN,NaN,NaN,曇,--,18.8
122,2014-5-27,79,火,0,牛肉すき焼き風,423.0,NaN,NaN,NaN,曇,--,23.7
95,2014-4-15,82,火,0,ポーク生姜焼き,370.0,NaN,NaN,NaN,快晴,--,19.7
71,2014-3-11,89,火,0,肉じゃが,397.0,NaN,NaN,NaN,快晴,--,8.7
76,2014-3-18,90,火,1,チーズ入りハンバーグ,400.0,NaN,NaN,NaN,晴れ,--,18.9
90,2014-4-8,96,火,1,肉団子のシチュー,353.0,NaN,NaN,NaN,快晴,--,20.1
56,2014-2-18,99,火,0,海老フライとホタテ串カツ,426.0,NaN,NaN,NaN,晴れ,--,6.8
66,2014-3-4,100,火,1,回鍋肉,413.0,NaN,NaN,NaN,晴れ,--,8.3
1,2013-11-19,101,火,1,手作りヒレカツ,NaN,NaN,NaN,NaN,快晴,--,17.0
61,2014-2-25,104,火,0,マーボ豆腐,396.0,NaN,NaN,NaN,快晴,--,10.5
42,2014-1-28,120,火,0,海老フライタルタル,445.0,NaN,NaN,NaN,快晴,--,12.6
47,2014-2-4,121,火,1,さわら焼味噌掛け,430.0,NaN,NaN,NaN,雨,0,3.8
25,2013-12-24,122,火,0,さっくりメンチカツ,NaN,NaN,NaN,NaN,快晴,--,11.5
85,2014-4-1,125,火,1,メンチカツ,377.0,NaN,NaN,NaN,薄曇,--,16.1
37,2014-1-21,129,火,1,サバ焼味噌掛け,447.0,NaN,NaN,NaN,快晴,--,10.4
32,2014-1-14,129,火,1,鶏の照り焼きマスタード,376.0,NaN,NaN,NaN,晴れ,--,5.8
28,2014-1-7,131,火,0,カレー入りソーセージカツ,404.0,NaN,NaN,NaN,快晴,--,7.3
21,2013-12-17,145,火,0,手作りヒレカツ,NaN,NaN,ママの会,NaN,曇,--,10.8
6,2013-11-26,145,火,0,豚のスタミナ炒め,NaN,NaN,NaN,NaN,快晴,--,17.9
11,2013-12-3,153,火,1,厚揚げ豚生姜炒め,NaN,NaN,NaN,NaN,快晴,--,13.9
16,2013-12-10,155,火,0,やわらかロースのサムジョン,NaN,NaN,NaN,1.0,曇,0.5,7.1

In [27]:
train[train['week'] == '火'].sort_values(by='y', ascending=False)

,datetime,y,week,soldout,name,kcal,remarks,event,payday,weather,precipitation,temperature
16,2013-12-10,155,火,0,やわらかロースのサムジョン,NaN,NaN,NaN,1.0,曇,0.5,7.1
11,2013-12-3,153,火,1,厚揚げ豚生姜炒め,NaN,NaN,NaN,NaN,快晴,--,13.9
21,2013-12-17,145,火,0,手作りヒレカツ,NaN,NaN,ママの会,NaN,曇,--,10.8
6,2013-11-26,145,火,0,豚のスタミナ炒め,NaN,NaN,NaN,NaN,快晴,--,17.9
28,2014-1-7,131,火,0,カレー入りソーセージカツ,404.0,NaN,NaN,NaN,快晴,--,7.3
32,2014-1-14,129,火,1,鶏の照り焼きマスタード,376.0,NaN,NaN,NaN,晴れ,--,5.8
37,2014-1-21,129,火,1,サバ焼味噌掛け,447.0,NaN,NaN,NaN,快晴,--,10.4
85,2014-4-1,125,火,1,メンチカツ,377.0,NaN,NaN,NaN,薄曇,--,16.1
25,2013-12-24,122,火,0,さっくりメンチカツ,NaN,NaN,NaN,NaN,快晴,--,11.5
47,2014-2-4,121,火,1,さわら焼味噌掛け,430.0,NaN,NaN,NaN,雨,0,3.8
42,2014-1-28,120,火,0,海老フライタルタル,445.0,NaN,NaN,NaN,快晴,--,12.6
61,2014-2-25,104,火,0,マーボ豆腐,396.0,NaN,NaN,NaN,快晴,--,10.5
1,2013-11-19,101,火,1,手作りヒレカツ,NaN,NaN,NaN,NaN,快晴,--,17.0
66,2014-3-4,100,火,1,回鍋肉,413.0,NaN,NaN,NaN,晴れ,--,8.3
56,2014-2-18,99,火,0,海老フライとホタテ串カツ,426.0,NaN,NaN,NaN,晴れ,--,6.8
90,2014-4-8,96,火,1,肉団子のシチュー,353.0,NaN,NaN,NaN,快晴,--,20.1
76,2014-3-18,90,火,1,チーズ入りハンバーグ,400.0,NaN,NaN,NaN,晴れ,--,18.9
71,2014-3-11,89,火,0,肉じゃが,397.0,NaN,NaN,NaN,快晴,--,8.7
95,2014-4-15,82,火,0,ポーク生姜焼き,370.0,NaN,NaN,NaN,快晴,--,19.7
122,2014-5-27,79,火,0,牛肉すき焼き風,423.0,NaN,NaN,NaN,曇,--,23.7
100,2014-4-22,78,火,1,マーボ豆腐,382.0,NaN,NaN,NaN,曇,--,18.8
80,2014-3-25,77,火,0,手作りひれかつ,407.0,NaN,NaN,NaN,快晴,--,18.9
117,2014-5-20,71,火,0,鶏の味噌漬け焼き,425.0,NaN,NaN,NaN,薄曇,--,23.9
112,2014-5-13,70,火,1,白身魚唐揚げ野菜餡かけ,428.0,NaN,NaN,NaN,雨,0,18.6
183,2014-8-26,68,火,0,キーマカレー,400.0,NaN,NaN,NaN,雨,0,26.2
188,2014-9-2,68,火,1,名古屋味噌カツ,440.0,手作りの味,NaN,NaN,晴れ,--,29.1
137,2014-6-17,63,火,0,ポークソテー韓国ソース,427.0,NaN,NaN,NaN,薄曇,--,27.6
193,2014-9-9,63,火,0,ハンバーグデミソース,460.0,NaN,NaN,NaN,晴れ,--,26.8
142,2014-6-24,61,火,0,鶏のトマトシチュー,430.0,NaN,NaN,NaN,曇,0,23.7
127,2014-6-3,59,火,0,ゴーヤチャンプルー,418.0,NaN,NaN,NaN,薄曇,--,27.0
132,2014-6-10,56,火,0,カレイ唐揚げ野菜餡かけ,426.0,NaN,NaN,1.0,曇,--,25.5
152,2014-7-8,56,火,0,かじきの甘辛煮,370.0,NaN,NaN,NaN,晴れ,--,29.7
197,2014-9-16,56,火,0,チーズメンチカツ,438.0,NaN,NaN,NaN,晴れ,--,28.8
147,2014-7-1,54,火,0,カレイ唐揚げ夏野菜あん,362.0,NaN,NaN,NaN,曇,--,28.3
171,2014-8-5,54,火,1,鶏肉のカレー唐揚,400.0,NaN,NaN,NaN,快晴,--,34.3
161,2014-7-22,53,火,0,チンジャオロース,409.0,NaN,NaN,NaN,晴れ,--,30.2
178,2014-8-19,53,火,1,牛スキヤキ,385.0,NaN,NaN,NaN,晴れ,--,33.3
166,2014-7-29,52,火,0,バーベキューチキン,449.0,NaN,NaN,NaN,晴れ,--,30.4
157,2014-7-15,51,火,0,豚冷シャブ野菜添え,324.0,NaN,NaN,NaN,晴れ,--,30.3
176,2014-8-12,40,火,1,厚切ハムカツ,400.0,NaN,NaN,NaN,雨,0,29.4
206,2014-9-30,40,火,0,鶏肉とカシューナッツ炒め,398.0,NaN,NaN,NaN,快晴,--,28.1

## 曜日が月曜日の時のyの平均値を見てみましょう
- 今までの応用です。まず、trainから曜日が月曜日の条件で抜きだし、yを選択した上で、その後に平均値を求める関数を使います

In [32]:
train_mon = train[train['week'] == '月']

In [34]:
train_mon['y'].mean()

94.05128205128206

In [35]:
train[train['week'] == '月']['y'].mean()

94.05128205128206

# 実習

1.test.csvを変数testとして読み込もう

In [36]:
test = pd.read_csv('test.csv')

2.testの先頭行を確認しましょう

In [38]:
test.head()

,datetime,week,soldout,name,kcal,remarks,event,payday,weather,precipitation,temperature
0,2014-10-1,水,1,メンチカツ,420.0,NaN,NaN,NaN,雨,0,20.2
1,2014-10-2,木,0,バーベキューチキン,415.0,NaN,NaN,NaN,曇,--,23.9
2,2014-10-3,金,0,豚肉のマスタード焼き,405.0,NaN,NaN,NaN,晴れ,--,28.7
3,2014-10-6,月,1,麻婆春雨,400.0,NaN,NaN,NaN,雨,0.5,21.5
4,2014-10-7,火,0,厚揚げ肉みそ炒め,430.0,NaN,NaN,NaN,晴れ,--,22.1

3.testの基本統計量を調べてみよう

In [39]:
test.describe()

         soldout        kcal  payday  temperature
count  40.000000   36.000000     2.0    40.000000
mean    0.425000  421.083333     1.0    18.665000
std     0.500641   13.626392     0.0     4.401838
min     0.000000  396.000000     1.0     9.200000
25%     0.000000  411.500000     1.0    15.250000
50%     0.000000  420.000000     1.0    19.000000
75%     1.000000  428.500000     1.0    21.650000
max     1.000000  460.000000     1.0    28.700000

4.trainのtemperatureの平均値を求めてみよう

In [40]:
train['temperature'].mean()

19.252173913043478

5.trainのtemperatureが平均以上のデータだけを選択してみよう

In [47]:
train[train['temperature'] >= train['temperature'].mean()]

,datetime,y,week,soldout,name,kcal,remarks,event,payday,weather,precipitation,temperature
0,2013-11-18,90,月,0,厚切りイカフライ,NaN,NaN,NaN,NaN,快晴,--,19.8
90,2014-4-8,96,火,1,肉団子のシチュー,353.0,NaN,NaN,NaN,快晴,--,20.1
92,2014-4-10,87,木,0,鶏の唐揚げおろしソース,362.0,NaN,NaN,1.0,晴れ,--,21.3
95,2014-4-15,82,火,0,ポーク生姜焼き,370.0,NaN,NaN,NaN,快晴,--,19.7
96,2014-4-16,57,水,0,カレイ唐揚げ野菜あんかけ,330.0,NaN,NaN,NaN,薄曇,--,21.5
...,...,...,...,...,...,...,...,...,...,...,...,...
202,2014-9-24,59,水,1,白身魚のマスタード焼き,408.0,NaN,NaN,NaN,曇,0,24.8
203,2014-9-25,50,木,0,牛カルビ焼き肉,394.0,NaN,NaN,NaN,曇,0,25.4
204,2014-9-26,45,金,0,ランチビュッフェ,NaN,スペシャルメニュー（800円）,キャリアアップ支援セミナー,NaN,晴れ,--,27.1
205,2014-9-29,56,月,1,豚肉と玉子の炒め,404.0,NaN,NaN,NaN,快晴,--,26.6
206,2014-9-30,40,火,0,鶏肉とカシューナッツ炒め,398.0,NaN,NaN,NaN,快晴,--,28.1

6.trainで今度はyとweekの2つのカラムを選択したい。どうしたらいいだろう？
- []をもう一つ使う

In [44]:
test_dim = ['1', '2']

In [45]:
test_dim

['1', '2']

In [43]:
train['y']

0       90
1      101
2      118
3      120
4      130
      ...
202     59
203     50
204     45
205     56
206     40
Name: y, Length: 207, dtype: int64

In [42]:
train[['y', 'week']]

       y week
0     90    月
1    101    火
2    118    水
3    120    木
4    130    金
..   ...  ...
202   59    水
203   50    木
204   45    金
205   56    月
206   40    火

[207 rows x 2 columns]